server:
  port: 8080 # Puerto interno uniforme

spring:
  application:
    name: microservicio-camiones

  # CONFIGURACI√ìN DE POSTGRESQL
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # CONFIGURACI√ìN DE JPA
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: true

# üó∫Ô∏è CONFIGURACI√ìN DE LA API DE RUTE OSRM (Para el DistanceService)
osrm:
  # URL interna del servicio OSRM (usada por DistanceService.java)
  base-url: http://osrm:5000/route/v1/driving/