server:
  port: 8084 # Puerto de escucha para este microservicio

spring:
  application:
    name: microservicio-integracion

# üó∫Ô∏è CONFIGURACI√ìN DE LA API DE RUTE OSRM
# Este servicio consume el contenedor OSRM que corre en el puerto 5000 dentro de Docker.
osrm:
  # La URL interna del servicio OSRM dentro de la red Docker
  base-url: http://osrm:5000/route/v1/driving/

# Nota: Si estuvieras usando Google Maps, aqu√≠ ir√≠a la API key y la URL base.